### PR TITLE
Allow maxCookieAge to be specified

### PR DESCRIPTION
**Pull request by suprememoocow**
Currently fflip uses a `maxAge` value when setting the cookie of 900000, or 15 minutes.

This PR keeps the current default, but allows the user to override the value. 

For example, we would prefer a value of one month. This PR will allow us to override the value.

### CODE REVIEW

**Comment by suprememoocow** [comment]
Looks like the build broke due to modules being no longer supported in node 0.8.x. Would you mind if I removed 0.8 from the `.travis.yml` file?

**Comment by FredKSchott** [comment]
Hey @suprememoocow, thanks for the PR! Sorry for the long wait, December was a busy month.

Just pushed https://github.com/FredKSchott/fflip/pull/9 to fix that travis issue, I think dropping support for v0.8 is a fine compromise for continuing development. I'll let you know when that gets merged and you can rebase onto master.

**Comment by FredKSchott** [comment]
#9 was just merged, please rebase off of master to get tests passing and then it's good to merge!

Also if you have time to answer, I'd love to know how you're using this library. Personal, company, in production, etc.

**Comment by suprememoocow** [comment]
Hi @FredKSchott,

> Also if you have time to answer, I'd love to know how you're using this library. Personal, company, in production, etc.

We're using it for [Gitter](https://gitter.im). We've even got a little UI where people can opt-in or -out of features (see http://next.gitter.im).

Since I submitted this PR, we've actually made some more changes to the way we use FFlip. See https://github.com/suprememoocow/fflip/pull/1. I haven't created a PR for it yet, but please let me know if it's something you would find useful in fflip.

Basically, we wanted to be able to have a bunch of criteria interacting with one another, for example:
* Enable this feature for users a, b, c (for eg, let's call it `usernameCriteria`)
* Enable this feature for 10% of users (`percentageUsersCriteria`)
* Disable this feature in IE10 and lower (`disabledBrowsersCriteria`)

Unfortunately, the way criteria are currently specified, this wasn't possible, so I added a new feature, which I call veto voting (for want of a better name) 

Each criteria can return one of three values:
* `true` if the criteria votes for the feature toggle to being enabled
* `false` if the criteria vetoes the feature toggle from being enabled
* `undefined/null` if the criteria abstains from voting

A criteria will then be enabled when it obtains at least one vote (`true`) from the present criteria without receiving any vetoes (`false`). 

This way, the criteria in the example above might interact as follows:
* For user "a" running Chrome, the votes will be
  * `usernameCriteria` -> `true` (vote)
  * `percentageUsersCriteria` -> `undefined` (abstain)
  * `disabledBrowsersCriteria` -> `undefined` (abstain)
  * Therefore, the feature will be enabled.

* For user "a" running **IE10**, the votes will be
  * `usernameCriteria` -> `true` (vote)
  * `percentageUsersCriteria` -> `undefined` (abstain)
  * `disabledBrowsersCriteria` -> `false` (veto)
  * Therefore the feature will be disabled

* For user "x" (who matches `percentageUsersCriteria`) running Chrome, the votes will be
  * `usernameCriteria` -> `undefined` (abstain)
  * `percentageUsersCriteria` -> `true` (vote)
  * `disabledBrowsersCriteria` -> `undefined` (abstain)
  * Therefore the feature will be enabled

* For user "y" (who does not match `percentageUsersCriteria`) running Chrome, the votes will be
  * `usernameCriteria` -> `undefined` (abstain)
  * `percentageUsersCriteria` -> `undefined` (abstain)
  * `disabledBrowsersCriteria` -> `undefined` (abstain)
  * Therefore the feature will be disabled

This might seem a little bit complicated, but it gives us the expressive power of having multiple interacting criteria. Since it's enabled by setting `useVetoVoting:true` in the config, it's also backwards compatible. 

Is this something you would be interested in? Would you like me to create a PR for it?

**Comment by suprememoocow** [comment]
@FredKSchott just rebased from upstream, so your changes are now in

**Comment by FredKSchott** [comment]
@suprememoocow so happy to hear that Gitter is using this! We used Gitter on the request repo and always saw a lot of good questions come in through there.

I Love the veto feature! That is definitely a use case that would extend outside of just Gitter. If we added the ability to define whether on/off takes precedence in the face of conflict (it sounds like "off"/veto always takes precedence in your situation) that could make it even more flexible.

If you're able I'd appreciate any PR you can get together to add that feature into master. I'm happy to work on the documentation as well if that's something standing in the way.

Thanks again for the contribution, merging now :clap: :clap: :clap:

**Comment by FredKSchott** [comment]
Seems like something wrong with my npm config, I'll get this pushed up to npm tomorrow

**Pull request merged**
